name: Go

on:
  push:
    branches:
      - master
  pull_request:

env:
  # renovate: datasource=golang-version depName=golang
  GO_VERSION: '1.24.1'

  # renovate: datasource=github-releases depName=golangci/golangci-lint
  GOLANGCI_LINT_VERSION: 'v1.64.7'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Set up Go
      uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5
      with:
        go-version: '${{ env.GO_VERSION }}'
      id: go

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -cover ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5
        with:
          go-version: '${{ env.GO_VERSION }}'
        id: go

      - name: golangci-lint
        uses: golangci/golangci-lint-action@4696ba8babb6127d732c3c6dde519db15edab9ea # v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
